version: "3.8"
services:
  ostis:
    build:
      dockerfile: ostis.Dockerfile
      context: ./
    ports:
      - "8000:8000"
      - "8090:8090"
      - "55770:55770"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 50
  app:
    depends_on:
      ostis:
        condition: service_healthy
    build:
      dockerfile: wink-back.Dockerfile
      context: ./
      args:
        - "--no-cache"
    restart: on-failure
    environment:
      - "uri=ws://ostis:8090/ws_json"
    ports:
      - "8080:8080"